### ISSUE TITLE
Campaing Description

### ISSUE THREAD

**Issue by fable-lake** [knyghtmare/AOI_Rework#1]
I was looking at the main file and noticed that something fancy was needed for Description, so as I wrote in the early stages of the AOI plot, I had an idea for it, but I forgot about it and today, while looking on my docs, I noticed it in my files, and then I saw that something was needed to the description of the campaign, so I adjusted it.

Seems to fit, but can be adjusted.

_… Being a drop of rain among few in the vanishing distance, I was looking for a way that would lead me to the fallen happiness … But I failed … I left those who I love without a chance for a new beginning … For a chance on my return and being one with her …  I failed but … I chose … I chose to stand along those who can't fight alone … I decided to be a sun beam … Small fading beam forming a spherical golden shell of hope …  I chose to be the Sun of Hope._

Erlornas, Commander of the Branch of the Sun

(Expert Level 7 scenarios)

**Comment by knyghtmare** [comment]
Fixed via 86ee38d78b0d381a464c604d501192b59fd6fe55
